name = "Thaumiel23"
author = "Tokebe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92209c46c3bdb22ff7173fdc000b4ea38d57ce7e73fb34a0ac6763d66087be4d"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
