name = "Thaumiel23"
author = "Tokebe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb3d4864dce7e8fc0dd44df1321bcd5334e359e5f666825a0b5be6bc6af6250f"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
